apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: label-sync
  namespace: kubeedge-prowbot
spec:
  schedule: "19 2 7 * *"  # Every 2:17 at Sunday
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: label-sync
    spec:
      template:
        spec:
          containers:
            - name: label-sync
              image: gcr.io/k8s-prow/label_sync:v20210113-cdd2f173ce
              args:
              - --config=/etc/config/labels.yaml
              - --confirm=true
              - --orgs=kubeedge
              - --token=/etc/github/oauth
              volumeMounts:
              - name: oauth
                mountPath: /etc/github
                readOnly: true
              - name: config
                mountPath: /etc/config
                readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: oauth-token
          - name: config
            configMap:
              name: labels
