---
apiVersion: batch/v1
kind: Job
metadata:
  name: label-sync
  namespace: kubeedge-prowbot
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        name: label-sync
    spec:
      restartPolicy: Never  # https://github.com/kubernetes/kubernetes/issues/54870
      containers:
      - name: label-sync
        image: gcr.io/k8s-prow/label_sync:v20210113-cdd2f173ce
        args:
        - --config=/etc/config/labels.yaml
        - --confirm=true
        - --orgs=kubeedge
        - --token=/etc/github/oauth
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: labels
